### ISSUE TITLE
new update

### ISSUE THREAD

**Issue by Trulosek** [happyzleaf/PixelmonOverlayBroadcaster#10]
It does not work on the latest update for Pixelmon

**Comment by GyroGyro** [comment]
> It does not work on the latest update for Pixelmon

same

**Comment by hqppyz** [comment]
I'm currently working on a fix.

**Comment by hqppyz** [comment]
Fixed in the [latest release](https://ore.spongepowered.org/happyzlife/PixelmonOverlay/versions/1.1.1). Thanks for reporting.
