### ISSUE TITLE
Add a way to configure the position the broadcast gui appears on the screen

### ISSUE THREAD

**Issue by ColinF1** [happyzleaf/PixelmonOverlayBroadcaster#12]
I would like to be able to pic a spot for the broadcast because it hides behind a journey map feature :(
![unknown](https://user-images.githubusercontent.com/29806639/86544531-9f791900-bef5-11ea-8176-e0447d28b2e9.png)

**Comment by hqppyz** [comment]
The rendering is done client-side and I cannot do much about it. Move the journeymap away instead.
