### ISSUE TITLE
Just some other features someone missed 

### ISSUE THREAD

**Issue by KhaozFrost** [happyzleaf/PixelmonOverlayBroadcaster#4]
Rare Spawn Events
```
Legendary
Ultra Beast
Shiny
Aura
```

(Toggles for each of course so you can enable or disable the ones you want)
"&AA &b&l%pokemonNname%&a has spawned in a &e&l%biomeName%&a biome"

Seconds to display for (so its not static and always on screen per announcement so 1 may last on screen longer then others)

**Comment by hqppyz** [comment]
We've discussed it in discord and it's gonna be implemented in another way, so I'm closing this
