### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 879492767** [happyzleaf/PixelmonOverlayBroadcaster#6]
https://paste.ubuntu.com/p/6Nz7fsFhmW/
if don't add a overlays, will have this error
I use PixelmonOverlay with XpanD's PixelmonBroadcasts

**Comment by hqppyz** [comment]
There are a couple of things I still need to fix about the api. Unfortunately I can't code for at least 8/9 days due to my final exams.

**Comment by hqppyz** [comment]
I think this isn't an issue anymore.
If it happens again, I will need a new log with all the related stuff info, like PixelmonBroadcasts version and such.
